import { Module } from '@nestjs/common';
import { JwtModule } from '@nestjs/jwt';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ConstantController } from './constant.controller';
import { ConstantService } from './constant.service';
import { Config } from '../../../config/config';
import {
  Axe,
  Compatibilitees,
  Convert,
  Longitudinales,
  Mod,
  PSat,
  Primaire,
  Prod,
  ProduitsType,
  Reco,
  Sup,
  Tableau1,
  Tableau11,
  Tableau12,
  TableauAngle2,
  TableauBilles,
  TableauBusesCaracteristique,
  TableauListeBuses,
  TableauMark,
  TableauMesh,
  TableauP,
  TableauQ,
  TableauR,
  TableauRR,
  TableauRW,
  TableauS,
  TableauSelect,
  Temporaire,
  Topo,
  Transversales,
  TypeVoie,
  Voie,
  _V15,
  _V154,
} from '../../database/model/entities';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      Axe,
      Compatibilitees,
      Convert,
      Longitudinales,
      Mod,
      PSat,
      Primaire,
      Prod,
      ProduitsType,
      Reco,
      Sup,
      Tableau1,
      Tableau11,
      Tableau12,
      TableauAngle2,
      TableauBilles,
      TableauBusesCaracteristique,
      TableauListeBuses,
      TableauMark,
      TableauMesh,
      TableauP,
      TableauQ,
      TableauR,
      TableauRR,
      TableauRW,
      TableauS,
      TableauSelect,
      Temporaire,
      Topo,
      Transversales,
      TypeVoie,
      Voie,
      _V15,
      _V154,
    ]),
    JwtModule.register({ secret: Config.JWT_SECRET }),
  ],
  controllers: [ConstantController],
  providers: [ConstantService],
})
export class ConstantModule {}
