version: "3.7"
services:
  mysql:
    image: mysql
    container_name: mysql-sartools
    restart: unless-stopped
    ports:
      - "6633:3306"
    networks:
      sartools:
        ipv4_address: 172.228.104.2
    volumes:
      - .docker/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: sartools
      MYSQL_ROOT_PASSWORD: sartools@2023
      MYSQL_USER: sartools
      MYSQL_PASSWORD: sartools2023
    command: --default-authentication-plugin=mysql_native_password
networks:
  sartools:
    name: sartools
    driver: bridge
    ipam:
      config:
        - subnet: 172.228.104.0/24
          gateway: 172.228.104.1
