import { _V15 } from '@modules/database/model/_v15.entity';
import { _V154 } from '@modules/database/model/_v154.entity';
import { Axe } from '@modules/database/model/axe.entity';
import { Compatibilitees } from '@modules/database/model/compalibilitees.entity';
import { Convert } from '@modules/database/model/convert.entity';
import { Longitudinales } from '@modules/database/model/longitudinales.entity';
import { Mod } from '@modules/database/model/mod.entity';
import { PSat } from '@modules/database/model/p-sat.entity';
import { Primaire } from '@modules/database/model/primaire.entity';
import { Prod } from '@modules/database/model/prod.entity';
import { ProduitsType } from '@modules/database/model/produits-type.entity';
import { Reco } from '@modules/database/model/reco.entity';
import { Sup } from '@modules/database/model/sup.entity';
import { TableauAngle2 } from '@modules/database/model/tableau-angle-2.entity';
import { TableauBilles } from '@modules/database/model/tableau-billes.entity';
import { TableauBusesCaracteristique } from '@modules/database/model/tableau-buses-caracteristique.entity';
import { TableauListeBuses } from '@modules/database/model/tableau-liste-buses.entity';
import { TableauMark } from '@modules/database/model/tableau-mark.entity';
import { TableauMesh } from '@modules/database/model/tableau-mesh.entity';
import { TableauP } from '@modules/database/model/tableau-p.entity';
import { TableauQ } from '@modules/database/model/tableau-q.entity';
import { TableauR } from '@modules/database/model/tableau-r.entity';
import { TableauRR } from '@modules/database/model/tableau-rr.entity';
import { TableauRW } from '@modules/database/model/tableau-rw.entity';
import { TableauS } from '@modules/database/model/tableau-s.entity';
import { TableauSelect } from '@modules/database/model/tableau-select.entity';
import { Tableau11 } from '@modules/database/model/tableau1-1.entity';
import { Tableau1 } from '@modules/database/model/tableau1.entity';
import { Tableau12 } from '@modules/database/model/tableau1_2.entity';
import { Temporaire } from '@modules/database/model/temporaire.entity';
import { Topo } from '@modules/database/model/topo.entity';
import { Transversales } from '@modules/database/model/transversales.entity';
import { TypeVoie } from '@modules/database/model/type-voie.entity';
import { Voie } from '@modules/database/model/voie.entity';

export class GetAllConstantResponseDto {
  _v15: _V15[];
  _v154: _V154[];
  axe: Axe[];
  compatibilitees: Compatibilitees[];
  convert: Convert[];
  longitudinales: Longitudinales[];
  mod: Mod[];
  pSat: PSat[];
  primaire: Primaire[];
  prod: Prod[];
  produitsType: ProduitsType[];
  reco: Reco[];
  sup: Sup[];
  tableauAngle2: TableauAngle2[];
  tableauBilles: TableauBilles[];
  tableauBusesCaracteristiqueRepository: TableauBusesCaracteristique[];
  tableauListeBusesRepository: TableauListeBuses[];
  tableauMarkRepository: TableauMark[];
  tableauMeshRepository: TableauMesh[];
  tableauPRepository: TableauP[];
  tableauQRepository: TableauQ[];
  tableauRRepository: TableauR[];
  tableauRRRepository: TableauRR[];
  tableauRWRepository: TableauRW[];
  tableauSRepository: TableauS[];
  tableauSelectRepository: TableauSelect[];
  tableau12Repository: Tableau12[];
  tableau11Repository: Tableau11[];
  tableau1Repository: Tableau1[];
  temporaireRepository: Temporaire[];
  topoRepository: Topo[];
  transversalesRepository: Transversales[];
  typeVoieRepository: TypeVoie[];
  voieRepository: Voie[];
}
