export enum ErrorCode {
  INVALID_ACCESS_TOKEN = 'INVALID_ACCESS_TOKEN',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_EXISTED = 'USER_EXISTED',
  INVALID_EFFECTIVE_TIME = 'INVALID_EFFECTIVE_TIME',
  INVALID_UPDATE_CONSTANT_INPUT = 'INVALID_UPDATE_CONSTANT_INPUT',
  USER_INACTIVED = 'USER_INACTIVED',
  USER_DELETED = 'USER_DELETED',
  MAPBOX_REQUEST_FAILED = 'MAPBOX_REQUEST_FAILED',
  MAILJET_SEND_EMAIL_FAILED = "MAILJET_SEND_EMAIL_FAILED",
}
